name: CI/CD for Bond Analytics Dashboard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv add pytest
          uv sync

      - name: Run tests
        run: |
          uv run pytest tests/test.py

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            set -e
            if [ -d "fixed_income_dashboard/.git" ]; then
              git -C fixed_income_dashboard pull
            else
              git clone https://github.com/mvoss02/fixed_income_dashboard.git
            fi
            cd fixed_income_dashboard/
            git pull origin main

            # Manually inject the API key as an environment variable
            export API_KEY=${{ secrets.API_KEY }}

            # Set the environment variable for the uv workspace
            # make ingest-data
            make stop-docker
            make run-docker-vm
